### ISSUE TITLE
Review: Transfer "use-media-breakpoints" npm name to tywmick/use-media-breakpoints

### ISSUE THREAD

**Issue by talves** [talves/use-media-breakpoints#1]
Email from @tywmick:
Hi, Tony!

I made a React hook called useMediaBreakpoints (https://github.com/tywmick/use-media-breakpoints) for using screen width breakpoints in React, inspired by Bootstrap’s media-breakpoint Sass mixins (https://getbootstrap.com/docs/4.5/layout/overview/#responsive-breakpoints) . I was thinking of publishing it to npm under the name “use-media-breakpoints” and then discovered your project (https://www.npmjs.com/package/use-media-breakpoints) there!

Looking at your code, it seems we’ve taken different approaches, so I don’t know that it’d be possible to merge at all, so I was wondering: given it’s been seven months since your project’s publishing and its last commit and you haven’t added documentation yet, mind if I take over the “use-media-breakpoints” name on npm?

Regards,
Ty

**Comment by talves** [comment]
@tywmick I admit the lack of documentation is a bummer, since I did not circle back to it once I wrote this React Hook. It might have helped you to determine what the strategy of this hook was trying to accomplish.

I've created a [`codesandbox` example][codesandbox] to show the use of the hook. 

The example includes a hook called [`use-bootstrap-breakpoints`][bootstrap], which is your hook built using this library and the default values of your library default breakpoint values (bootstrap).


[codesandbox]: https://codesandbox.io/s/example-of-use-media-breakpoints-6ryf9
[bootstrap]: https://codesandbox.io/s/example-of-use-media-breakpoints-6ryf9?file=/src/use-bootstrap-breakpoints.js

**Comment by talves** [comment]
@tywmick I named the npm library based on the use of `media` queries, which is what the library is using rather than window size. This is an un-opinionated use of media breakpoints as you can see from the use of the library which allowed me to create a clone (which is opinionated) of [`tywmick/use-media-breakpoints`][tywmick].

Can you please explain why you would want to replace my library with your library for the npm name `use-media-breakpoints`? Do you feel my library isn't representative of the name I've used?

I want to give you the opportunity to sway my opinion, which at the moment is more to keeping things the way they are.

Thanks.

[tywmick]: https://github.com/tywmick/use-media-breakpoints

**Comment by TyMick** [comment]
@talves Sorry, didn't mean to give you more work to do! I had thought that without any documentation yet that the project had remained a personal utility rather than something you were still meaning to share. I should have asked that question specifically instead of assuming. 🤦🏼‍♂️

Now that you mention it, yeah, my project's name isn't quite as accurate. I named it after Bootstrap's Sass mixins `media-breakpoint-up`, `media-breakpoint-down`, `media-breakpoint-only`, and `media-breakpoint-between`, which also only deal with window width breakpoints, but, you know, they do actually use media queries in their code, unlike my hook... And they're only meant to be used in a Bootstrap context—they aren't standalone projects.

I should just change my project's name. And hey, looks like [use-window-width-breakpoints](https://www.npmjs.com/package/use-window-width-breakpoints) is available!

Thanks for your patience, and for helping me work out my naming scheme. 🙏🏼

**Comment by talves** [comment]
No problem @tywmick . It will help me get some documentation spun up also. I'll probably use the example once I get the time freed up.

The reason you probably couldn't see me in the npm thread is because my reply email is different than the default email for npm (I use the +npm identifier to be able to identify email groups).
